apiVersion: v1
kind: Service
metadata:
  labels:
    service: udacity-translator-service
  name: udacity-translator-service
spec:
  ports:
  - name: "8501"
    port: 8501
    targetPort: 80
  selector:
    service: udacity-translator-service 